src-git libremesh https://github.com/libremesh/lime-packages.git;master
src-link librerouter /home/fede/REPOS/lime-dev/repos/librerouteros/packages
src-git tmate https://github.com/project-openwrt/openwrt-tmate.git
src-git ampr https://github.com/javierbrk/ampr-openwrt.git;patch-1
