version: '3.8'

services:
  librerouteros-builder:
    build:
      context: .
      dockerfile: Dockerfile.librerouteros
    container_name: librerouteros-build
    volumes:
      # Mount source code
      - .:/workspace/src:ro
      # Persistent download cache
      - librerouteros-dl:/workspace/dl
      # Build output
      - librerouteros-build:/workspace/build
      # Firmware output
      - ./bin:/workspace/output
    working_dir: /workspace/src
    environment:
      - FORCE=1
      - MAKEFLAGS=-j4
      - DL_DIR=/workspace/dl
      - BUILD_DIR=/workspace/build
    stdin_open: true
    tty: true
    user: builder
    
  # Interactive shell for debugging
  librerouteros-shell:
    build:
      context: .
      dockerfile: Dockerfile.librerouteros
    container_name: librerouteros-shell
    volumes:
      - .:/workspace/src
      - librerouteros-dl:/workspace/dl
      - librerouteros-build:/workspace/build
      - ./bin:/workspace/output
    working_dir: /workspace/src
    environment:
      - FORCE=1
    stdin_open: true
    tty: true
    user: builder
    command: bash

volumes:
  librerouteros-dl:
    driver: local
  librerouteros-build:
    driver: local